"use client";
import { useEffect,useState } from "react"; import AnalysisDashboard from "../components/AnalysisDashboard"; import { api } from "../lib/api";
export default function HomePage(){
const [mode,setMode]=useState("login"),[token,setToken]=useState(""),[name,setName]=useState("Demo User"),[email,setEmail]=useState("demo@example.com"),[password,setPassword]=useState("password123");
const [targetRole,setTargetRole]=useState("Software Engineer"),[jobDescription,setJobDescription]=useState(""),[resumeText,setResumeText]=useState(""),[resumeFile,setResumeFile]=useState(null),[result,setResult]=useState(null),[vectorStatus,setVectorStatus]=useState(null),[vectorCheckedAt,setVectorCheckedAt]=useState(""),[autoRefreshVector,setAutoRefreshVector]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(false);
const auth=async()=>{const d=await (mode==="login"?api.login({email,password}):api.register({name,email,password})); d.token?setToken(d.token):setError(d.message||"Auth failed");};
const check=async()=>{if(!token)return; const s=await api.vectorStatus(token); setVectorStatus(s); setVectorCheckedAt(new Date().toLocaleString());};
useEffect(()=>{ if(!token||!autoRefreshVector)return; check(); const id=setInterval(check,30000); return ()=>clearInterval(id); },[token,autoRefreshVector]);
const analyze=async()=>{setLoading(true); setError(""); const d=await api.analyze({token,targetRole,jobDescription,resumeText,resumeFile}); d.result?setResult(d.result):setError(d.message||"Analysis failed"); setLoading(false);};
return <main className="container"><h1>AI Resume Analyzer</h1>
{!token&&<div className="card"><h2>{mode==="login"?"Login":"Register"}</h2>{mode==="register"&&<><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} /></>}<label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} /><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} /><div style={{display:"flex",gap:8,marginTop:12}}><button onClick={auth}>{mode==="login"?"Login":"Create account"}</button><button className="secondary" onClick={()=>setMode(mode==="login"?"register":"login")}>Switch</button></div></div>}
{token&&<><div className="card"><h2>Vector Store Health</h2><button className="secondary" onClick={check}>Check Vector Status</button>
<label style={{display:"inline-flex",gap:8,alignItems:"center",marginLeft:10}}><input type="checkbox" checked={autoRefreshVector} onChange={e=>setAutoRefreshVector(e.target.checked)} style={{width:"auto"}}/>Auto-refresh every 30s</label>
{vectorStatus&&<div className="status-row"><span className={`status-badge ${vectorStatus.ok?"status-ok":"status-error"}`}>{vectorStatus.ok?"Healthy":"Unhealthy"}</span><span><b>Provider:</b> {vectorStatus.provider}</span>{vectorCheckedAt&&<span className="muted">Last checked: {vectorCheckedAt}</span>}</div>}
{vectorStatus?.error&&<p style={{color:"#fda4af"}}><b>Error:</b> {vectorStatus.error}</p>}</div>
<div className="card"><h2>Analyze Resume</h2><label>Target Role</label><input value={targetRole} onChange={e=>setTargetRole(e.target.value)} /><label>Job Description</label><textarea rows={8} value={jobDescription} onChange={e=>setJobDescription(e.target.value)} /><label>Paste Resume Text</label><textarea rows={8} value={resumeText} onChange={e=>setResumeText(e.target.value)} /><label>Upload Resume (.pdf/.docx/.txt)</label><input type="file" accept=".pdf,.docx,.txt" onChange={e=>setResumeFile(e.target.files?.[0]||null)} /><div style={{marginTop:10}}><button onClick={analyze} disabled={loading}>{loading?"Analyzing...":"Run AI Analysis"}</button></div></div></>}
{error&&<div className="card"><p style={{color:"#fca5a5"}}>{error}</p></div>}{result&&<AnalysisDashboard {...{score:result.jobMatchScore,skillGap:result.skillGap,atsKeywords:result.atsKeywords,strengths:result.strengths,weaknesses:result.weaknesses,improvementTips:result.improvementTips,portfolioSuggestions:result.portfolioSuggestions,summary:result.summary}} />}</main>;
}
